name: Docker publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (optional)"
        required: false
  push:
    branches:
      - "master"

jobs:
  
  docker-package:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false

    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.20.x"

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          driver-opts: network=host

      - run: make patch

      - id: versioning
        run: echo "tag=$(cat ./version)" >> $GITHUB_ENV

      - name: Docker packaging Offline installer
        env:
          VERSIONTAG: ${{ env.tag }}
          SSH_PRIVATE_KEY: ${{ secrets.ISSAC_KEY }}

        run: |
          # Run the 'package_offline' command in ./harbor/Makefile
          cd ./harbor
          sed -i 's/package_offline: update_prepare_version compile build/package_offline: update_prepare_version/' Makefile
          cat Makefile
          # make package_offline

          # Setup SSH key
          mkdir -p ~/.ssh/
          echo "${{ secrets.ISSAC_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Disable host key checking
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

          # Send the output file to the certain server
          # chown ubuntu:ubuntu ./harbor/harbor-offline-installer*
          # scp -i ~/.ssh/id_rsa ./harbor/harbor-offline-installer* ubuntu@3.36.98.17:/home/ubuntu/
